/**
 * XI SDK Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InvoiceDetailResponseServiceresponseResponsepreamble model module.
 * @module model/InvoiceDetailResponseServiceresponseResponsepreamble
 * @version 1.0.0
 */
class InvoiceDetailResponseServiceresponseResponsepreamble {
    /**
     * Constructs a new <code>InvoiceDetailResponseServiceresponseResponsepreamble</code>.
     * @alias module:model/InvoiceDetailResponseServiceresponseResponsepreamble
     */
    constructor() { 
        
        InvoiceDetailResponseServiceresponseResponsepreamble.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InvoiceDetailResponseServiceresponseResponsepreamble</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InvoiceDetailResponseServiceresponseResponsepreamble} obj Optional instance to populate.
     * @return {module:model/InvoiceDetailResponseServiceresponseResponsepreamble} The populated <code>InvoiceDetailResponseServiceresponseResponsepreamble</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvoiceDetailResponseServiceresponseResponsepreamble();

            if (data.hasOwnProperty('responsestatus')) {
                obj['responsestatus'] = ApiClient.convertToType(data['responsestatus'], 'String');
            }
            if (data.hasOwnProperty('statuscode')) {
                obj['statuscode'] = ApiClient.convertToType(data['statuscode'], 'String');
            }
            if (data.hasOwnProperty('responsemessage')) {
                obj['responsemessage'] = ApiClient.convertToType(data['responsemessage'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InvoiceDetailResponseServiceresponseResponsepreamble</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InvoiceDetailResponseServiceresponseResponsepreamble</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['responsestatus'] && !(typeof data['responsestatus'] === 'string' || data['responsestatus'] instanceof String)) {
            throw new Error("Expected the field `responsestatus` to be a primitive type in the JSON string but got " + data['responsestatus']);
        }
        // ensure the json data is a string
        if (data['statuscode'] && !(typeof data['statuscode'] === 'string' || data['statuscode'] instanceof String)) {
            throw new Error("Expected the field `statuscode` to be a primitive type in the JSON string but got " + data['statuscode']);
        }
        // ensure the json data is a string
        if (data['responsemessage'] && !(typeof data['responsemessage'] === 'string' || data['responsemessage'] instanceof String)) {
            throw new Error("Expected the field `responsemessage` to be a primitive type in the JSON string but got " + data['responsemessage']);
        }

        return true;
    }


}



/**
 * @member {String} responsestatus
 */
InvoiceDetailResponseServiceresponseResponsepreamble.prototype['responsestatus'] = undefined;

/**
 * @member {String} statuscode
 */
InvoiceDetailResponseServiceresponseResponsepreamble.prototype['statuscode'] = undefined;

/**
 * @member {String} responsemessage
 */
InvoiceDetailResponseServiceresponseResponsepreamble.prototype['responsemessage'] = undefined;






export default InvoiceDetailResponseServiceresponseResponsepreamble;

