/**
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderCreateV7RequestShipToInfo model module.
 * @module model/OrderCreateV7RequestShipToInfo
 * @version 1.0.0
 */
class OrderCreateV7RequestShipToInfo {
    /**
     * Constructs a new <code>OrderCreateV7RequestShipToInfo</code>.
     * The shipping information provided by the reseller.
     * @alias module:model/OrderCreateV7RequestShipToInfo
     */
    constructor() { 
        
        OrderCreateV7RequestShipToInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderCreateV7RequestShipToInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderCreateV7RequestShipToInfo} obj Optional instance to populate.
     * @return {module:model/OrderCreateV7RequestShipToInfo} The populated <code>OrderCreateV7RequestShipToInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderCreateV7RequestShipToInfo();

            if (data.hasOwnProperty('addressId')) {
                obj['addressId'] = ApiClient.convertToType(data['addressId'], 'String');
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = ApiClient.convertToType(data['contact'], 'String');
            }
            if (data.hasOwnProperty('companyName')) {
                obj['companyName'] = ApiClient.convertToType(data['companyName'], 'String');
            }
            if (data.hasOwnProperty('addressLine1')) {
                obj['addressLine1'] = ApiClient.convertToType(data['addressLine1'], 'String');
            }
            if (data.hasOwnProperty('addressLine2')) {
                obj['addressLine2'] = ApiClient.convertToType(data['addressLine2'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('shippingNotes')) {
                obj['shippingNotes'] = ApiClient.convertToType(data['shippingNotes'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderCreateV7RequestShipToInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderCreateV7RequestShipToInfo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['addressId'] && !(typeof data['addressId'] === 'string' || data['addressId'] instanceof String)) {
            throw new Error("Expected the field `addressId` to be a primitive type in the JSON string but got " + data['addressId']);
        }
        // ensure the json data is a string
        if (data['contact'] && !(typeof data['contact'] === 'string' || data['contact'] instanceof String)) {
            throw new Error("Expected the field `contact` to be a primitive type in the JSON string but got " + data['contact']);
        }
        // ensure the json data is a string
        if (data['companyName'] && !(typeof data['companyName'] === 'string' || data['companyName'] instanceof String)) {
            throw new Error("Expected the field `companyName` to be a primitive type in the JSON string but got " + data['companyName']);
        }
        // ensure the json data is a string
        if (data['addressLine1'] && !(typeof data['addressLine1'] === 'string' || data['addressLine1'] instanceof String)) {
            throw new Error("Expected the field `addressLine1` to be a primitive type in the JSON string but got " + data['addressLine1']);
        }
        // ensure the json data is a string
        if (data['addressLine2'] && !(typeof data['addressLine2'] === 'string' || data['addressLine2'] instanceof String)) {
            throw new Error("Expected the field `addressLine2` to be a primitive type in the JSON string but got " + data['addressLine2']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is a string
        if (data['postalCode'] && !(typeof data['postalCode'] === 'string' || data['postalCode'] instanceof String)) {
            throw new Error("Expected the field `postalCode` to be a primitive type in the JSON string but got " + data['postalCode']);
        }
        // ensure the json data is a string
        if (data['countryCode'] && !(typeof data['countryCode'] === 'string' || data['countryCode'] instanceof String)) {
            throw new Error("Expected the field `countryCode` to be a primitive type in the JSON string but got " + data['countryCode']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['shippingNotes'] && !(typeof data['shippingNotes'] === 'string' || data['shippingNotes'] instanceof String)) {
            throw new Error("Expected the field `shippingNotes` to be a primitive type in the JSON string but got " + data['shippingNotes']);
        }
        // ensure the json data is a string
        if (data['phoneNumber'] && !(typeof data['phoneNumber'] === 'string' || data['phoneNumber'] instanceof String)) {
            throw new Error("Expected the field `phoneNumber` to be a primitive type in the JSON string but got " + data['phoneNumber']);
        }

        return true;
    }


}



/**
 * The ID references the resellers address in Ingram Micro's system for shipping. Provided to resellers during the onboarding process.
 * @member {String} addressId
 */
OrderCreateV7RequestShipToInfo.prototype['addressId'] = undefined;

/**
 * The company contact provided by the reseller.
 * @member {String} contact
 */
OrderCreateV7RequestShipToInfo.prototype['contact'] = undefined;

/**
 * The reseller's company name or the End-User's Name
 * @member {String} companyName
 */
OrderCreateV7RequestShipToInfo.prototype['companyName'] = undefined;

/**
 * The street address and building or house number the order will be shipped to.
 * @member {String} addressLine1
 */
OrderCreateV7RequestShipToInfo.prototype['addressLine1'] = undefined;

/**
 * The apartment number the order will be shipped to.
 * @member {String} addressLine2
 */
OrderCreateV7RequestShipToInfo.prototype['addressLine2'] = undefined;

/**
 * The city the order will be shipped to.
 * @member {String} city
 */
OrderCreateV7RequestShipToInfo.prototype['city'] = undefined;

/**
 * The state the order will be shipped to.
 * @member {String} state
 */
OrderCreateV7RequestShipToInfo.prototype['state'] = undefined;

/**
 * End User Name
 * @member {String} postalCode
 */
OrderCreateV7RequestShipToInfo.prototype['postalCode'] = undefined;

/**
 * The zip or postal code the order will be shipped to.
 * @member {String} countryCode
 */
OrderCreateV7RequestShipToInfo.prototype['countryCode'] = undefined;

/**
 * The company contact email address.
 * @member {String} email
 */
OrderCreateV7RequestShipToInfo.prototype['email'] = undefined;

/**
 * 
 * @member {String} shippingNotes
 */
OrderCreateV7RequestShipToInfo.prototype['shippingNotes'] = undefined;

/**
 * The company contact phone number.
 * @member {String} phoneNumber
 */
OrderCreateV7RequestShipToInfo.prototype['phoneNumber'] = undefined;






export default OrderCreateV7RequestShipToInfo;

