/**
 * XI Sdk Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrderCreateResponseServiceresponse from './OrderCreateResponseServiceresponse';

/**
 * The OrderCreateResponse model module.
 * @module model/OrderCreateResponse
 * @version 1.0.0
 */
class OrderCreateResponse {
    /**
     * Constructs a new <code>OrderCreateResponse</code>.
     * Response schema for order create endpoint
     * @alias module:model/OrderCreateResponse
     */
    constructor() { 
        
        OrderCreateResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderCreateResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderCreateResponse} obj Optional instance to populate.
     * @return {module:model/OrderCreateResponse} The populated <code>OrderCreateResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderCreateResponse();

            if (data.hasOwnProperty('serviceresponse')) {
                obj['serviceresponse'] = OrderCreateResponseServiceresponse.constructFromObject(data['serviceresponse']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderCreateResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderCreateResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `serviceresponse`
        if (data['serviceresponse']) { // data not null
          OrderCreateResponseServiceresponse.validateJSON(data['serviceresponse']);
        }

        return true;
    }


}



/**
 * @member {module:model/OrderCreateResponseServiceresponse} serviceresponse
 */
OrderCreateResponse.prototype['serviceresponse'] = undefined;






export default OrderCreateResponse;

