/**
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInnerChoicesInner from './OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInnerChoicesInner';

/**
 * The OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner model module.
 * @module model/OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner
 * @version 1.0.0
 */
class OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner {
    /**
     * Constructs a new <code>OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner</code>.
     * @alias module:model/OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner
     */
    constructor() { 
        
        OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner} obj Optional instance to populate.
     * @return {module:model/OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner} The populated <code>OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner();

            if (data.hasOwnProperty('attributeName')) {
                obj['attributeName'] = ApiClient.convertToType(data['attributeName'], 'String');
            }
            if (data.hasOwnProperty('attributeValue')) {
                obj['attributeValue'] = ApiClient.convertToType(data['attributeValue'], 'String');
            }
            if (data.hasOwnProperty('attributeDescription')) {
                obj['attributeDescription'] = ApiClient.convertToType(data['attributeDescription'], 'String');
            }
            if (data.hasOwnProperty('attributeHint')) {
                obj['attributeHint'] = ApiClient.convertToType(data['attributeHint'], 'String');
            }
            if (data.hasOwnProperty('choices')) {
                obj['choices'] = ApiClient.convertToType(data['choices'], [OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInnerChoicesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['attributeName'] && !(typeof data['attributeName'] === 'string' || data['attributeName'] instanceof String)) {
            throw new Error("Expected the field `attributeName` to be a primitive type in the JSON string but got " + data['attributeName']);
        }
        // ensure the json data is a string
        if (data['attributeValue'] && !(typeof data['attributeValue'] === 'string' || data['attributeValue'] instanceof String)) {
            throw new Error("Expected the field `attributeValue` to be a primitive type in the JSON string but got " + data['attributeValue']);
        }
        // ensure the json data is a string
        if (data['attributeDescription'] && !(typeof data['attributeDescription'] === 'string' || data['attributeDescription'] instanceof String)) {
            throw new Error("Expected the field `attributeDescription` to be a primitive type in the JSON string but got " + data['attributeDescription']);
        }
        // ensure the json data is a string
        if (data['attributeHint'] && !(typeof data['attributeHint'] === 'string' || data['attributeHint'] instanceof String)) {
            throw new Error("Expected the field `attributeHint` to be a primitive type in the JSON string but got " + data['attributeHint']);
        }
        if (data['choices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['choices'])) {
                throw new Error("Expected the field `choices` to be an array in the JSON data but got " + data['choices']);
            }
            // validate the optional field `choices` (array)
            for (const item of data['choices']) {
                OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInnerChoicesInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * The name of the vendor mandatory field
 * @member {String} attributeName
 */
OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner.prototype['attributeName'] = undefined;

/**
 * The value of the vendor mandatory field
 * @member {String} attributeValue
 */
OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner.prototype['attributeValue'] = undefined;

/**
 * The description of the vendor mandatory field
 * @member {String} attributeDescription
 */
OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner.prototype['attributeDescription'] = undefined;

/**
 * The hint of the vendor mandatory field.
 * @member {String} attributeHint
 */
OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner.prototype['attributeHint'] = undefined;

/**
 * 
 * @member {Array.<module:model/OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInnerChoicesInner>} choices
 */
OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner.prototype['choices'] = undefined;






export default OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInner;

