/**
 * XI SDK Resellers
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderDeleteRequestServicerequestRequestpreamble model module.
 * @module model/OrderDeleteRequestServicerequestRequestpreamble
 * @version 6.0
 */
class OrderDeleteRequestServicerequestRequestpreamble {
    /**
     * Constructs a new <code>OrderDeleteRequestServicerequestRequestpreamble</code>.
     * @alias module:model/OrderDeleteRequestServicerequestRequestpreamble
     * @param isocountrycode {String} Country that Order is being place in.
     * @param customerNumber {String} Account number order will be billed to. INGRAM MICRO ACCOUNT NUMBER REQUIRED
     */
    constructor(isocountrycode, customerNumber) { 
        
        OrderDeleteRequestServicerequestRequestpreamble.initialize(this, isocountrycode, customerNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, isocountrycode, customerNumber) { 
        obj['isocountrycode'] = isocountrycode;
        obj['customerNumber'] = customerNumber;
    }

    /**
     * Constructs a <code>OrderDeleteRequestServicerequestRequestpreamble</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderDeleteRequestServicerequestRequestpreamble} obj Optional instance to populate.
     * @return {module:model/OrderDeleteRequestServicerequestRequestpreamble} The populated <code>OrderDeleteRequestServicerequestRequestpreamble</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderDeleteRequestServicerequestRequestpreamble();

            if (data.hasOwnProperty('isocountrycode')) {
                obj['isocountrycode'] = ApiClient.convertToType(data['isocountrycode'], 'String');
            }
            if (data.hasOwnProperty('customerNumber')) {
                obj['customerNumber'] = ApiClient.convertToType(data['customerNumber'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderDeleteRequestServicerequestRequestpreamble</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderDeleteRequestServicerequestRequestpreamble</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OrderDeleteRequestServicerequestRequestpreamble.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['isocountrycode'] && !(typeof data['isocountrycode'] === 'string' || data['isocountrycode'] instanceof String)) {
            throw new Error("Expected the field `isocountrycode` to be a primitive type in the JSON string but got " + data['isocountrycode']);
        }
        // ensure the json data is a string
        if (data['customerNumber'] && !(typeof data['customerNumber'] === 'string' || data['customerNumber'] instanceof String)) {
            throw new Error("Expected the field `customerNumber` to be a primitive type in the JSON string but got " + data['customerNumber']);
        }

        return true;
    }


}

OrderDeleteRequestServicerequestRequestpreamble.RequiredProperties = ["isocountrycode", "customerNumber"];

/**
 * Country that Order is being place in.
 * @member {String} isocountrycode
 */
OrderDeleteRequestServicerequestRequestpreamble.prototype['isocountrycode'] = undefined;

/**
 * Account number order will be billed to. INGRAM MICRO ACCOUNT NUMBER REQUIRED
 * @member {String} customerNumber
 */
OrderDeleteRequestServicerequestRequestpreamble.prototype['customerNumber'] = undefined;






export default OrderDeleteRequestServicerequestRequestpreamble;

