/**
 * XI SDK Resellers
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner model module.
 * @module model/OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner
 * @version 6.0
 */
class OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner {
    /**
     * Constructs a new <code>OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner</code>.
     * @alias module:model/OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner
     */
    constructor() { 
        
        OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner} obj Optional instance to populate.
     * @return {module:model/OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner} The populated <code>OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner();

            if (data.hasOwnProperty('serialnumber')) {
                obj['serialnumber'] = ApiClient.convertToType(data['serialnumber'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['serialnumber'] && !(typeof data['serialnumber'] === 'string' || data['serialnumber'] instanceof String)) {
            throw new Error("Expected the field `serialnumber` to be a primitive type in the JSON string but got " + data['serialnumber']);
        }

        return true;
    }


}



/**
 * serial number of the ordered SKU
 * @member {String} serialnumber
 */
OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner.prototype['serialnumber'] = undefined;






export default OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerSerialnumberdetailsInner;

