/**
 * XI Sdk Resellers
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriod from './PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriod';
import PriceAndAvailabilityResponseInnerSubscriptionPriceInnerGroupsInner from './PriceAndAvailabilityResponseInnerSubscriptionPriceInnerGroupsInner';
import PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInner from './PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInner';
import PriceAndAvailabilityResponseInnerSubscriptionPriceInnerSubscriptionPeriodInner from './PriceAndAvailabilityResponseInnerSubscriptionPriceInnerSubscriptionPeriodInner';

/**
 * The PriceAndAvailabilityResponseInnerSubscriptionPriceInner model module.
 * @module model/PriceAndAvailabilityResponseInnerSubscriptionPriceInner
 * @version 1.0.0
 */
class PriceAndAvailabilityResponseInnerSubscriptionPriceInner {
    /**
     * Constructs a new <code>PriceAndAvailabilityResponseInnerSubscriptionPriceInner</code>.
     * @alias module:model/PriceAndAvailabilityResponseInnerSubscriptionPriceInner
     */
    constructor() { 
        
        PriceAndAvailabilityResponseInnerSubscriptionPriceInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PriceAndAvailabilityResponseInnerSubscriptionPriceInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PriceAndAvailabilityResponseInnerSubscriptionPriceInner} obj Optional instance to populate.
     * @return {module:model/PriceAndAvailabilityResponseInnerSubscriptionPriceInner} The populated <code>PriceAndAvailabilityResponseInnerSubscriptionPriceInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PriceAndAvailabilityResponseInnerSubscriptionPriceInner();

            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'Number');
            }
            if (data.hasOwnProperty('planId')) {
                obj['planId'] = ApiClient.convertToType(data['planId'], 'String');
            }
            if (data.hasOwnProperty('planUId')) {
                obj['planUId'] = ApiClient.convertToType(data['planUId'], 'String');
            }
            if (data.hasOwnProperty('planName')) {
                obj['planName'] = ApiClient.convertToType(data['planName'], 'String');
            }
            if (data.hasOwnProperty('planDescription')) {
                obj['planDescription'] = ApiClient.convertToType(data['planDescription'], 'String');
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], [PriceAndAvailabilityResponseInnerSubscriptionPriceInnerGroupsInner]);
            }
            if (data.hasOwnProperty('billingPeriod')) {
                obj['billingPeriod'] = PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriod.constructFromObject(data['billingPeriod']);
            }
            if (data.hasOwnProperty('subscriptionPeriod')) {
                obj['subscriptionPeriod'] = ApiClient.convertToType(data['subscriptionPeriod'], [PriceAndAvailabilityResponseInnerSubscriptionPriceInnerSubscriptionPeriodInner]);
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], [PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PriceAndAvailabilityResponseInnerSubscriptionPriceInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PriceAndAvailabilityResponseInnerSubscriptionPriceInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['planId'] && !(typeof data['planId'] === 'string' || data['planId'] instanceof String)) {
            throw new Error("Expected the field `planId` to be a primitive type in the JSON string but got " + data['planId']);
        }
        // ensure the json data is a string
        if (data['planUId'] && !(typeof data['planUId'] === 'string' || data['planUId'] instanceof String)) {
            throw new Error("Expected the field `planUId` to be a primitive type in the JSON string but got " + data['planUId']);
        }
        // ensure the json data is a string
        if (data['planName'] && !(typeof data['planName'] === 'string' || data['planName'] instanceof String)) {
            throw new Error("Expected the field `planName` to be a primitive type in the JSON string but got " + data['planName']);
        }
        // ensure the json data is a string
        if (data['planDescription'] && !(typeof data['planDescription'] === 'string' || data['planDescription'] instanceof String)) {
            throw new Error("Expected the field `planDescription` to be a primitive type in the JSON string but got " + data['planDescription']);
        }
        if (data['groups']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['groups'])) {
                throw new Error("Expected the field `groups` to be an array in the JSON data but got " + data['groups']);
            }
            // validate the optional field `groups` (array)
            for (const item of data['groups']) {
                PriceAndAvailabilityResponseInnerSubscriptionPriceInnerGroupsInner.validateJSON(item);
            };
        }
        // validate the optional field `billingPeriod`
        if (data['billingPeriod']) { // data not null
          PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriod.validateJSON(data['billingPeriod']);
        }
        if (data['subscriptionPeriod']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['subscriptionPeriod'])) {
                throw new Error("Expected the field `subscriptionPeriod` to be an array in the JSON data but got " + data['subscriptionPeriod']);
            }
            // validate the optional field `subscriptionPeriod` (array)
            for (const item of data['subscriptionPeriod']) {
                PriceAndAvailabilityResponseInnerSubscriptionPriceInnerSubscriptionPeriodInner.validateJSON(item);
            };
        }
        if (data['options']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['options'])) {
                throw new Error("Expected the field `options` to be an array in the JSON data but got " + data['options']);
            }
            // validate the optional field `options` (array)
            for (const item of data['options']) {
                PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} index
 */
PriceAndAvailabilityResponseInnerSubscriptionPriceInner.prototype['index'] = undefined;

/**
 * Id of the plan.
 * @member {String} planId
 */
PriceAndAvailabilityResponseInnerSubscriptionPriceInner.prototype['planId'] = undefined;

/**
 * @member {String} planUId
 */
PriceAndAvailabilityResponseInnerSubscriptionPriceInner.prototype['planUId'] = undefined;

/**
 * Name of the plan.
 * @member {String} planName
 */
PriceAndAvailabilityResponseInnerSubscriptionPriceInner.prototype['planName'] = undefined;

/**
 * The description of the plan.
 * @member {String} planDescription
 */
PriceAndAvailabilityResponseInnerSubscriptionPriceInner.prototype['planDescription'] = undefined;

/**
 * @member {Array.<module:model/PriceAndAvailabilityResponseInnerSubscriptionPriceInnerGroupsInner>} groups
 */
PriceAndAvailabilityResponseInnerSubscriptionPriceInner.prototype['groups'] = undefined;

/**
 * @member {module:model/PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriod} billingPeriod
 */
PriceAndAvailabilityResponseInnerSubscriptionPriceInner.prototype['billingPeriod'] = undefined;

/**
 * @member {Array.<module:model/PriceAndAvailabilityResponseInnerSubscriptionPriceInnerSubscriptionPeriodInner>} subscriptionPeriod
 */
PriceAndAvailabilityResponseInnerSubscriptionPriceInner.prototype['subscriptionPeriod'] = undefined;

/**
 * @member {Array.<module:model/PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInner>} options
 */
PriceAndAvailabilityResponseInnerSubscriptionPriceInner.prototype['options'] = undefined;






export default PriceAndAvailabilityResponseInnerSubscriptionPriceInner;

