/**
 * XI SDK Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductDetailResponseCiscoFields model module.
 * @module model/ProductDetailResponseCiscoFields
 * @version 1.0.0
 */
class ProductDetailResponseCiscoFields {
    /**
     * Constructs a new <code>ProductDetailResponseCiscoFields</code>.
     * Cisco product related information.
     * @alias module:model/ProductDetailResponseCiscoFields
     */
    constructor() { 
        
        ProductDetailResponseCiscoFields.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductDetailResponseCiscoFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductDetailResponseCiscoFields} obj Optional instance to populate.
     * @return {module:model/ProductDetailResponseCiscoFields} The populated <code>ProductDetailResponseCiscoFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductDetailResponseCiscoFields();

            if (data.hasOwnProperty('productSubGroup')) {
                obj['productSubGroup'] = ApiClient.convertToType(data['productSubGroup'], 'String');
            }
            if (data.hasOwnProperty('serviceProgramName')) {
                obj['serviceProgramName'] = ApiClient.convertToType(data['serviceProgramName'], 'String');
            }
            if (data.hasOwnProperty('itemCatalogCategory')) {
                obj['itemCatalogCategory'] = ApiClient.convertToType(data['itemCatalogCategory'], 'String');
            }
            if (data.hasOwnProperty('configurationIndicator')) {
                obj['configurationIndicator'] = ApiClient.convertToType(data['configurationIndicator'], 'String');
            }
            if (data.hasOwnProperty('internalBusinessEntity')) {
                obj['internalBusinessEntity'] = ApiClient.convertToType(data['internalBusinessEntity'], 'String');
            }
            if (data.hasOwnProperty('itemType')) {
                obj['itemType'] = ApiClient.convertToType(data['itemType'], 'String');
            }
            if (data.hasOwnProperty('globalListPrice')) {
                obj['globalListPrice'] = ApiClient.convertToType(data['globalListPrice'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductDetailResponseCiscoFields</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductDetailResponseCiscoFields</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['productSubGroup'] && !(typeof data['productSubGroup'] === 'string' || data['productSubGroup'] instanceof String)) {
            throw new Error("Expected the field `productSubGroup` to be a primitive type in the JSON string but got " + data['productSubGroup']);
        }
        // ensure the json data is a string
        if (data['serviceProgramName'] && !(typeof data['serviceProgramName'] === 'string' || data['serviceProgramName'] instanceof String)) {
            throw new Error("Expected the field `serviceProgramName` to be a primitive type in the JSON string but got " + data['serviceProgramName']);
        }
        // ensure the json data is a string
        if (data['itemCatalogCategory'] && !(typeof data['itemCatalogCategory'] === 'string' || data['itemCatalogCategory'] instanceof String)) {
            throw new Error("Expected the field `itemCatalogCategory` to be a primitive type in the JSON string but got " + data['itemCatalogCategory']);
        }
        // ensure the json data is a string
        if (data['configurationIndicator'] && !(typeof data['configurationIndicator'] === 'string' || data['configurationIndicator'] instanceof String)) {
            throw new Error("Expected the field `configurationIndicator` to be a primitive type in the JSON string but got " + data['configurationIndicator']);
        }
        // ensure the json data is a string
        if (data['internalBusinessEntity'] && !(typeof data['internalBusinessEntity'] === 'string' || data['internalBusinessEntity'] instanceof String)) {
            throw new Error("Expected the field `internalBusinessEntity` to be a primitive type in the JSON string but got " + data['internalBusinessEntity']);
        }
        // ensure the json data is a string
        if (data['itemType'] && !(typeof data['itemType'] === 'string' || data['itemType'] instanceof String)) {
            throw new Error("Expected the field `itemType` to be a primitive type in the JSON string but got " + data['itemType']);
        }
        // ensure the json data is a string
        if (data['globalListPrice'] && !(typeof data['globalListPrice'] === 'string' || data['globalListPrice'] instanceof String)) {
            throw new Error("Expected the field `globalListPrice` to be a primitive type in the JSON string but got " + data['globalListPrice']);
        }

        return true;
    }


}



/**
 * Cisco product sub-group
 * @member {String} productSubGroup
 */
ProductDetailResponseCiscoFields.prototype['productSubGroup'] = undefined;

/**
 * Cisco service program name
 * @member {String} serviceProgramName
 */
ProductDetailResponseCiscoFields.prototype['serviceProgramName'] = undefined;

/**
 * Cisco item catalog category
 * @member {String} itemCatalogCategory
 */
ProductDetailResponseCiscoFields.prototype['itemCatalogCategory'] = undefined;

/**
 * Cisco configuration indicator
 * @member {String} configurationIndicator
 */
ProductDetailResponseCiscoFields.prototype['configurationIndicator'] = undefined;

/**
 * Cisco internal business entity
 * @member {String} internalBusinessEntity
 */
ProductDetailResponseCiscoFields.prototype['internalBusinessEntity'] = undefined;

/**
 * Cisco item type
 * @member {String} itemType
 */
ProductDetailResponseCiscoFields.prototype['itemType'] = undefined;

/**
 * Cisco global list price
 * @member {String} globalListPrice
 */
ProductDetailResponseCiscoFields.prototype['globalListPrice'] = undefined;






export default ProductDetailResponseCiscoFields;

