/**
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner model module.
 * @module model/ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner
 * @version 1.0.0
 */
class ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner {
    /**
     * Constructs a new <code>ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner</code>.
     * @alias module:model/ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner
     */
    constructor() { 
        
        ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner} obj Optional instance to populate.
     * @return {module:model/ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner} The populated <code>ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner();

            if (data.hasOwnProperty('subscriptionPeriodUnit')) {
                obj['subscriptionPeriodUnit'] = ApiClient.convertToType(data['subscriptionPeriodUnit'], 'String');
            }
            if (data.hasOwnProperty('subscriptionPeriod')) {
                obj['subscriptionPeriod'] = ApiClient.convertToType(data['subscriptionPeriod'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['subscriptionPeriodUnit'] && !(typeof data['subscriptionPeriodUnit'] === 'string' || data['subscriptionPeriodUnit'] instanceof String)) {
            throw new Error("Expected the field `subscriptionPeriodUnit` to be a primitive type in the JSON string but got " + data['subscriptionPeriodUnit']);
        }
        // ensure the json data is a string
        if (data['subscriptionPeriod'] && !(typeof data['subscriptionPeriod'] === 'string' || data['subscriptionPeriod'] instanceof String)) {
            throw new Error("Expected the field `subscriptionPeriod` to be a primitive type in the JSON string but got " + data['subscriptionPeriod']);
        }

        return true;
    }


}



/**
 * Unit period of the subscription. Example, Years, Months
 * @member {String} subscriptionPeriodUnit
 */
ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner.prototype['subscriptionPeriodUnit'] = undefined;

/**
 * Length of the subscription. Example 1, 3
 * @member {String} subscriptionPeriod
 */
ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner.prototype['subscriptionPeriod'] = undefined;






export default ProductDetailResponseSubscriptionDetailsInnerSubscriptionPeriodInner;

