/**
 * XI Sdk Resellers
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductDetailResponseSubscriptionDetailsInnerBillingPeriod model module.
 * @module model/ProductDetailResponseSubscriptionDetailsInnerBillingPeriod
 * @version 1.0.0
 */
class ProductDetailResponseSubscriptionDetailsInnerBillingPeriod {
    /**
     * Constructs a new <code>ProductDetailResponseSubscriptionDetailsInnerBillingPeriod</code>.
     * Details of the subscription billing period. 
     * @alias module:model/ProductDetailResponseSubscriptionDetailsInnerBillingPeriod
     */
    constructor() { 
        
        ProductDetailResponseSubscriptionDetailsInnerBillingPeriod.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductDetailResponseSubscriptionDetailsInnerBillingPeriod</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductDetailResponseSubscriptionDetailsInnerBillingPeriod} obj Optional instance to populate.
     * @return {module:model/ProductDetailResponseSubscriptionDetailsInnerBillingPeriod} The populated <code>ProductDetailResponseSubscriptionDetailsInnerBillingPeriod</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductDetailResponseSubscriptionDetailsInnerBillingPeriod();

            if (data.hasOwnProperty('billingPeriodUnit')) {
                obj['billingPeriodUnit'] = ApiClient.convertToType(data['billingPeriodUnit'], 'String');
            }
            if (data.hasOwnProperty('billingPeriod')) {
                obj['billingPeriod'] = ApiClient.convertToType(data['billingPeriod'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductDetailResponseSubscriptionDetailsInnerBillingPeriod</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductDetailResponseSubscriptionDetailsInnerBillingPeriod</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['billingPeriodUnit'] && !(typeof data['billingPeriodUnit'] === 'string' || data['billingPeriodUnit'] instanceof String)) {
            throw new Error("Expected the field `billingPeriodUnit` to be a primitive type in the JSON string but got " + data['billingPeriodUnit']);
        }

        return true;
    }


}



/**
 * Billing unit period of the subscription. Example, Years, Months
 * @member {String} billingPeriodUnit
 */
ProductDetailResponseSubscriptionDetailsInnerBillingPeriod.prototype['billingPeriodUnit'] = undefined;

/**
 * Billing period of the subscription. Example 1, 3
 * @member {Number} billingPeriod
 */
ProductDetailResponseSubscriptionDetailsInnerBillingPeriod.prototype['billingPeriod'] = undefined;






export default ProductDetailResponseSubscriptionDetailsInnerBillingPeriod;

