/**
 * XI Sdk Resellers
 * For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VendorRequiredInfoRequestProductsInner model module.
 * @module model/VendorRequiredInfoRequestProductsInner
 * @version 1.0.0
 */
class VendorRequiredInfoRequestProductsInner {
    /**
     * Constructs a new <code>VendorRequiredInfoRequestProductsInner</code>.
     * @alias module:model/VendorRequiredInfoRequestProductsInner
     */
    constructor() { 
        
        VendorRequiredInfoRequestProductsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VendorRequiredInfoRequestProductsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VendorRequiredInfoRequestProductsInner} obj Optional instance to populate.
     * @return {module:model/VendorRequiredInfoRequestProductsInner} The populated <code>VendorRequiredInfoRequestProductsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VendorRequiredInfoRequestProductsInner();

            if (data.hasOwnProperty('ingramPartNumber')) {
                obj['ingramPartNumber'] = ApiClient.convertToType(data['ingramPartNumber'], 'String');
            }
            if (data.hasOwnProperty('vendorPartNumber')) {
                obj['vendorPartNumber'] = ApiClient.convertToType(data['vendorPartNumber'], 'String');
            }
            if (data.hasOwnProperty('planID')) {
                obj['planID'] = ApiClient.convertToType(data['planID'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VendorRequiredInfoRequestProductsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VendorRequiredInfoRequestProductsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ingramPartNumber'] && !(typeof data['ingramPartNumber'] === 'string' || data['ingramPartNumber'] instanceof String)) {
            throw new Error("Expected the field `ingramPartNumber` to be a primitive type in the JSON string but got " + data['ingramPartNumber']);
        }
        // ensure the json data is a string
        if (data['vendorPartNumber'] && !(typeof data['vendorPartNumber'] === 'string' || data['vendorPartNumber'] instanceof String)) {
            throw new Error("Expected the field `vendorPartNumber` to be a primitive type in the JSON string but got " + data['vendorPartNumber']);
        }

        return true;
    }


}



/**
 * Ingram Micro unique part number for the product.
 * @member {String} ingramPartNumber
 */
VendorRequiredInfoRequestProductsInner.prototype['ingramPartNumber'] = undefined;

/**
 * Vendor’s part number for the product. It can be either TS Product or Cloud Product vendorpartnumber.
 * @member {String} vendorPartNumber
 */
VendorRequiredInfoRequestProductsInner.prototype['vendorPartNumber'] = undefined;

/**
 * The ID of the subscription plan.
 * @member {Number} planID
 */
VendorRequiredInfoRequestProductsInner.prototype['planID'] = undefined;






export default VendorRequiredInfoRequestProductsInner;

