/**
 * XI Sdk Resellers
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.XiSdkResellers);
  }
}(this, function(expect, XiSdkResellers) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new XiSdkResellers.DealsDetailsResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DealsDetailsResponse', function() {
    it('should create an instance of DealsDetailsResponse', function() {
      // uncomment below and update the code to test DealsDetailsResponse
      //var instance = new XiSdkResellers.DealsDetailsResponse();
      //expect(instance).to.be.a(XiSdkResellers.DealsDetailsResponse);
    });

    it('should have the property dealId (base name: "dealId")', function() {
      // uncomment below and update the code to test the property dealId
      //var instance = new XiSdkResellers.DealsDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new XiSdkResellers.DealsDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property endUser (base name: "endUser")', function() {
      // uncomment below and update the code to test the property endUser
      //var instance = new XiSdkResellers.DealsDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property extendedMsrp (base name: "extendedMsrp")', function() {
      // uncomment below and update the code to test the property extendedMsrp
      //var instance = new XiSdkResellers.DealsDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property vendor (base name: "vendor")', function() {
      // uncomment below and update the code to test the property vendor
      //var instance = new XiSdkResellers.DealsDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property dealReceivedOn (base name: "dealReceivedOn")', function() {
      // uncomment below and update the code to test the property dealReceivedOn
      //var instance = new XiSdkResellers.DealsDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property dealExpiryDate (base name: "dealExpiryDate")', function() {
      // uncomment below and update the code to test the property dealExpiryDate
      //var instance = new XiSdkResellers.DealsDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property priceProtectionEndDate (base name: "priceProtectionEndDate")', function() {
      // uncomment below and update the code to test the property priceProtectionEndDate
      //var instance = new XiSdkResellers.DealsDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property currencyCode (base name: "currencyCode")', function() {
      // uncomment below and update the code to test the property currencyCode
      //var instance = new XiSdkResellers.DealsDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property endUserInfo (base name: "endUserInfo")', function() {
      // uncomment below and update the code to test the property endUserInfo
      //var instance = new XiSdkResellers.DealsDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property products (base name: "products")', function() {
      // uncomment below and update the code to test the property products
      //var instance = new XiSdkResellers.DealsDetailsResponse();
      //expect(instance).to.be();
    });

  });

}));
