/**
 * XI Sdk Resellers
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.XiSdkResellers);
  }
}(this, function(expect, XiSdkResellers) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DealsDetailsResponseProductsInner', function() {
    it('should create an instance of DealsDetailsResponseProductsInner', function() {
      // uncomment below and update the code to test DealsDetailsResponseProductsInner
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be.a(XiSdkResellers.DealsDetailsResponseProductsInner);
    });

    it('should have the property ingramPartNumber (base name: "ingramPartNumber")', function() {
      // uncomment below and update the code to test the property ingramPartNumber
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

    it('should have the property vendorPartNumber (base name: "vendorPartNumber")', function() {
      // uncomment below and update the code to test the property vendorPartNumber
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

    it('should have the property upc (base name: "upc")', function() {
      // uncomment below and update the code to test the property upc
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

    it('should have the property productDescription (base name: "productDescription")', function() {
      // uncomment below and update the code to test the property productDescription
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

    it('should have the property msrp (base name: "msrp")', function() {
      // uncomment below and update the code to test the property msrp
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

    it('should have the property extendedMSRP (base name: "extendedMSRP")', function() {
      // uncomment below and update the code to test the property extendedMSRP
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

    it('should have the property standardPrice (base name: "standardPrice")', function() {
      // uncomment below and update the code to test the property standardPrice
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

    it('should have the property approvedQuantity (base name: "approvedQuantity")', function() {
      // uncomment below and update the code to test the property approvedQuantity
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

    it('should have the property remainingQuantity (base name: "remainingQuantity")', function() {
      // uncomment below and update the code to test the property remainingQuantity
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

    it('should have the property comments (base name: "comments")', function() {
      // uncomment below and update the code to test the property comments
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

    it('should have the property specialConditions (base name: "specialConditions")', function() {
      // uncomment below and update the code to test the property specialConditions
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "startDate")', function() {
      // uncomment below and update the code to test the property startDate
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

    it('should have the property expirationDate (base name: "expirationDate")', function() {
      // uncomment below and update the code to test the property expirationDate
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

    it('should have the property daysRemaining (base name: "daysRemaining")', function() {
      // uncomment below and update the code to test the property daysRemaining
      //var instance = new XiSdkResellers.DealsDetailsResponseProductsInner();
      //expect(instance).to.be();
    });

  });

}));
