/**
 * Reseller API Documentation
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ResellerApiDocumentation);
  }
}(this, function(expect, ResellerApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ResellerApiDocumentation.FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner', function() {
    it('should create an instance of FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner', function() {
      // uncomment below and update the code to test FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner
      //var instance = new ResellerApiDocumentation.FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner();
      //expect(instance).to.be.a(ResellerApiDocumentation.FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner);
    });

    it('should have the property carrierCode (base name: "carrierCode")', function() {
      // uncomment below and update the code to test the property carrierCode
      //var instance = new ResellerApiDocumentation.FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner();
      //expect(instance).to.be();
    });

    it('should have the property shipVia (base name: "shipVia")', function() {
      // uncomment below and update the code to test the property shipVia
      //var instance = new ResellerApiDocumentation.FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner();
      //expect(instance).to.be();
    });

    it('should have the property carrierMode (base name: "carrierMode")', function() {
      // uncomment below and update the code to test the property carrierMode
      //var instance = new ResellerApiDocumentation.FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner();
      //expect(instance).to.be();
    });

    it('should have the property estimatedFreightCharge (base name: "estimatedFreightCharge")', function() {
      // uncomment below and update the code to test the property estimatedFreightCharge
      //var instance = new ResellerApiDocumentation.FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner();
      //expect(instance).to.be();
    });

    it('should have the property daysInTransit (base name: "daysInTransit")', function() {
      // uncomment below and update the code to test the property daysInTransit
      //var instance = new ResellerApiDocumentation.FreightResponseFreightEstimateResponseDistributionInnerCarrierListInner();
      //expect(instance).to.be();
    });

  });

}));
