/**
 * XI Sdk Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.XiSdkResellers);
  }
}(this, function(expect, XiSdkResellers) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new XiSdkResellers.FreightResponseFreightEstimateResponseDistributionInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FreightResponseFreightEstimateResponseDistributionInner', function() {
    it('should create an instance of FreightResponseFreightEstimateResponseDistributionInner', function() {
      // uncomment below and update the code to test FreightResponseFreightEstimateResponseDistributionInner
      //var instance = new XiSdkResellers.FreightResponseFreightEstimateResponseDistributionInner();
      //expect(instance).to.be.a(XiSdkResellers.FreightResponseFreightEstimateResponseDistributionInner);
    });

    it('should have the property shipFromBranchNumber (base name: "shipFromBranchNumber")', function() {
      // uncomment below and update the code to test the property shipFromBranchNumber
      //var instance = new XiSdkResellers.FreightResponseFreightEstimateResponseDistributionInner();
      //expect(instance).to.be();
    });

    it('should have the property carrierCode (base name: "carrierCode")', function() {
      // uncomment below and update the code to test the property carrierCode
      //var instance = new XiSdkResellers.FreightResponseFreightEstimateResponseDistributionInner();
      //expect(instance).to.be();
    });

    it('should have the property shipVia (base name: "shipVia")', function() {
      // uncomment below and update the code to test the property shipVia
      //var instance = new XiSdkResellers.FreightResponseFreightEstimateResponseDistributionInner();
      //expect(instance).to.be();
    });

    it('should have the property freightRate (base name: "freightRate")', function() {
      // uncomment below and update the code to test the property freightRate
      //var instance = new XiSdkResellers.FreightResponseFreightEstimateResponseDistributionInner();
      //expect(instance).to.be();
    });

    it('should have the property totalWeight (base name: "totalWeight")', function() {
      // uncomment below and update the code to test the property totalWeight
      //var instance = new XiSdkResellers.FreightResponseFreightEstimateResponseDistributionInner();
      //expect(instance).to.be();
    });

    it('should have the property transitDays (base name: "transitDays")', function() {
      // uncomment below and update the code to test the property transitDays
      //var instance = new XiSdkResellers.FreightResponseFreightEstimateResponseDistributionInner();
      //expect(instance).to.be();
    });

    it('should have the property carrierList (base name: "carrierList")', function() {
      // uncomment below and update the code to test the property carrierList
      //var instance = new XiSdkResellers.FreightResponseFreightEstimateResponseDistributionInner();
      //expect(instance).to.be();
    });

  });

}));
