/**
 * XI Sdk Resellers
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.XiSdkResellers);
  }
}(this, function(expect, XiSdkResellers) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrderCreateRequestOrdercreaterequestOrdercreatedetails', function() {
    it('should create an instance of OrderCreateRequestOrdercreaterequestOrdercreatedetails', function() {
      // uncomment below and update the code to test OrderCreateRequestOrdercreaterequestOrdercreatedetails
      //var instance = new XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails();
      //expect(instance).to.be.a(XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails);
    });

    it('should have the property customerponumber (base name: "customerponumber")', function() {
      // uncomment below and update the code to test the property customerponumber
      //var instance = new XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails();
      //expect(instance).to.be();
    });

    it('should have the property ordertype (base name: "ordertype")', function() {
      // uncomment below and update the code to test the property ordertype
      //var instance = new XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails();
      //expect(instance).to.be();
    });

    it('should have the property enduserordernumber (base name: "enduserordernumber")', function() {
      // uncomment below and update the code to test the property enduserordernumber
      //var instance = new XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails();
      //expect(instance).to.be();
    });

    it('should have the property billtosuffix (base name: "billtosuffix")', function() {
      // uncomment below and update the code to test the property billtosuffix
      //var instance = new XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails();
      //expect(instance).to.be();
    });

    it('should have the property shiptosuffix (base name: "shiptosuffix")', function() {
      // uncomment below and update the code to test the property shiptosuffix
      //var instance = new XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails();
      //expect(instance).to.be();
    });

    it('should have the property shiptoaddress (base name: "shiptoaddress")', function() {
      // uncomment below and update the code to test the property shiptoaddress
      //var instance = new XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails();
      //expect(instance).to.be();
    });

    it('should have the property carriercode (base name: "carriercode")', function() {
      // uncomment below and update the code to test the property carriercode
      //var instance = new XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails();
      //expect(instance).to.be();
    });

    it('should have the property thirdpartyfreightaccountnumber (base name: "thirdpartyfreightaccountnumber")', function() {
      // uncomment below and update the code to test the property thirdpartyfreightaccountnumber
      //var instance = new XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails();
      //expect(instance).to.be();
    });

    it('should have the property specialbidnumber (base name: "specialbidnumber")', function() {
      // uncomment below and update the code to test the property specialbidnumber
      //var instance = new XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails();
      //expect(instance).to.be();
    });

    it('should have the property lines (base name: "lines")', function() {
      // uncomment below and update the code to test the property lines
      //var instance = new XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails();
      //expect(instance).to.be();
    });

    it('should have the property extendedspecs (base name: "extendedspecs")', function() {
      // uncomment below and update the code to test the property extendedspecs
      //var instance = new XiSdkResellers.OrderCreateRequestOrdercreaterequestOrdercreatedetails();
      //expect(instance).to.be();
    });

  });

}));
