/**
 * XI Sdk Resellers
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.XiSdkResellers);
  }
}(this, function(expect, XiSdkResellers) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new XiSdkResellers.ProductDetailResponseSubscriptionDetailsInnerOptionsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductDetailResponseSubscriptionDetailsInnerOptionsInner', function() {
    it('should create an instance of ProductDetailResponseSubscriptionDetailsInnerOptionsInner', function() {
      // uncomment below and update the code to test ProductDetailResponseSubscriptionDetailsInnerOptionsInner
      //var instance = new XiSdkResellers.ProductDetailResponseSubscriptionDetailsInnerOptionsInner();
      //expect(instance).to.be.a(XiSdkResellers.ProductDetailResponseSubscriptionDetailsInnerOptionsInner);
    });

    it('should have the property resourceId (base name: "resourceId")', function() {
      // uncomment below and update the code to test the property resourceId
      //var instance = new XiSdkResellers.ProductDetailResponseSubscriptionDetailsInnerOptionsInner();
      //expect(instance).to.be();
    });

    it('should have the property resourceName (base name: "resourceName")', function() {
      // uncomment below and update the code to test the property resourceName
      //var instance = new XiSdkResellers.ProductDetailResponseSubscriptionDetailsInnerOptionsInner();
      //expect(instance).to.be();
    });

    it('should have the property vendorPartNumber (base name: "vendorPartNumber")', function() {
      // uncomment below and update the code to test the property vendorPartNumber
      //var instance = new XiSdkResellers.ProductDetailResponseSubscriptionDetailsInnerOptionsInner();
      //expect(instance).to.be();
    });

    it('should have the property minUnits (base name: "minUnits")', function() {
      // uncomment below and update the code to test the property minUnits
      //var instance = new XiSdkResellers.ProductDetailResponseSubscriptionDetailsInnerOptionsInner();
      //expect(instance).to.be();
    });

    it('should have the property maxUnits (base name: "maxUnits")', function() {
      // uncomment below and update the code to test the property maxUnits
      //var instance = new XiSdkResellers.ProductDetailResponseSubscriptionDetailsInnerOptionsInner();
      //expect(instance).to.be();
    });

    it('should have the property dependsOn (base name: "dependsOn")', function() {
      // uncomment below and update the code to test the property dependsOn
      //var instance = new XiSdkResellers.ProductDetailResponseSubscriptionDetailsInnerOptionsInner();
      //expect(instance).to.be();
    });

  });

}));
