/**
 * XI Sdk Resellers
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.XiSdkResellers);
  }
}(this, function(expect, XiSdkResellers) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new XiSdkResellers.ProductSearchResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductSearchResponse', function() {
    it('should create an instance of ProductSearchResponse', function() {
      // uncomment below and update the code to test ProductSearchResponse
      //var instance = new XiSdkResellers.ProductSearchResponse();
      //expect(instance).to.be.a(XiSdkResellers.ProductSearchResponse);
    });

    it('should have the property recordsFound (base name: "recordsFound")', function() {
      // uncomment below and update the code to test the property recordsFound
      //var instance = new XiSdkResellers.ProductSearchResponse();
      //expect(instance).to.be();
    });

    it('should have the property pageSize (base name: "pageSize")', function() {
      // uncomment below and update the code to test the property pageSize
      //var instance = new XiSdkResellers.ProductSearchResponse();
      //expect(instance).to.be();
    });

    it('should have the property pageNumber (base name: "pageNumber")', function() {
      // uncomment below and update the code to test the property pageNumber
      //var instance = new XiSdkResellers.ProductSearchResponse();
      //expect(instance).to.be();
    });

    it('should have the property catalog (base name: "catalog")', function() {
      // uncomment below and update the code to test the property catalog
      //var instance = new XiSdkResellers.ProductSearchResponse();
      //expect(instance).to.be();
    });

    it('should have the property subscriptionCatalog (base name: "subscriptionCatalog")', function() {
      // uncomment below and update the code to test the property subscriptionCatalog
      //var instance = new XiSdkResellers.ProductSearchResponse();
      //expect(instance).to.be();
    });

    it('should have the property nextPage (base name: "nextPage")', function() {
      // uncomment below and update the code to test the property nextPage
      //var instance = new XiSdkResellers.ProductSearchResponse();
      //expect(instance).to.be();
    });

    it('should have the property previousPage (base name: "previousPage")', function() {
      // uncomment below and update the code to test the property previousPage
      //var instance = new XiSdkResellers.ProductSearchResponse();
      //expect(instance).to.be();
    });

  });

}));
